---
# tasks - main.yml for nerve4-openvas-base

- include: rhel-install-openvas-base.yml
  when: 
    (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8") or
    (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8") or
    (ansible_distribution in "Rocky" and ansible_distribution_major_version == "8")